// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// MakeZ_C
double MakeZ_C(NumericVector pvals, int m);
RcppExport SEXP _TMTI_MakeZ_C(SEXP pvalsSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pvals(pvalsSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(MakeZ_C(pvals, m));
    return rcpp_result_gen;
END_RCPP
}
// MakeY_C
NumericVector MakeY_C(NumericVector pvals, int m);
RcppExport SEXP _TMTI_MakeY_C(SEXP pvalsSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pvals(pvalsSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(MakeY_C(pvals, m));
    return rcpp_result_gen;
END_RCPP
}
// MakeZ_C_nsmall
double MakeZ_C_nsmall(NumericVector pvals, int n, int m);
RcppExport SEXP _TMTI_MakeZ_C_nsmall(SEXP pvalsSEXP, SEXP nSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pvals(pvalsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(MakeZ_C_nsmall(pvals, n, m));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TMTI_MakeZ_C", (DL_FUNC) &_TMTI_MakeZ_C, 2},
    {"_TMTI_MakeY_C", (DL_FUNC) &_TMTI_MakeY_C, 2},
    {"_TMTI_MakeZ_C_nsmall", (DL_FUNC) &_TMTI_MakeZ_C_nsmall, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_TMTI(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
