# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Leading NA
#'
#' Returns the TMTI_infinity statistic from pre-sorted,
#' pre-truncated vector of p-values. If no truncation is used, set m_full = m
#'
#' @param pvals A NumericVector containing the truncated sorted p-values. It
#' is important that this vector: 1) contains only the truncated p-values (i.e,
#' those that fall below the truncation point) and 2) is sorted.
#' @param m The total (i.e., non-truncated) number of p-values.
#' @export
MakeZ_C <- function(pvals, m) {
    .Call('_TMTI_MakeZ_C', PACKAGE = 'TMTI', pvals, m)
}

#' Leading NA
#'
#' Returns the transformed p-values (Y) from pre-sorted p-values and
#' pre-truncated p-values. If not truncation is used, set m_full = m
#'
#' @param pvals A NumericVector containing the truncated sorted p-values. It
#' is important that this vector: 1) contains only the truncated p-values (i.e,
#' those that fall below the truncation point) and 2) is sorted.
#' @param m The total (i.e., non-truncated) number of p-values.
#' @export
MakeY_C <- function(pvals, m) {
    .Call('_TMTI_MakeY_C', PACKAGE = 'TMTI', pvals, m)
}

#' Leading NA
#'
#' Returns the transformed p-values (Y) from pre-sorted p-values and
#' pre-truncated p-values when n < m - 1
#'
#' @param pvals A NumericVector containing the truncated sorted p-values. It
#' is important that this vector: 1) contains only the truncated p-values (i.e,
#' those that fall below the truncation point) and 2) is sorted.
#' @param n A positive number (or Inf) indicating which type of local minimum
#' to consider. Defaults to Infm, corresponding to the global minimum.
#' @param m The total (i.e., non-truncated) number of p-values.
#' @export
MakeZ_C_nsmall <- function(pvals, n, m) {
    .Call('_TMTI_MakeZ_C_nsmall', PACKAGE = 'TMTI', pvals, n, m)
}

