# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Leading NA
#'
#' Returns the TMTI_infinity statistic from a pre-sorted vector of p-values
#'
#' @param pvals A NumericVector
#' @export
calc_TMTI_inf <- function(pvals) {
    .Call('_TMTI_calc_TMTI_inf', PACKAGE = 'TMTI', pvals)
}

#' Leading NA
#'
#' Returns the truncated TMTI_infinity statistic from pre-sorted,
#' pre-truncated p-values.
#'
#' @param pvals A NumericVector containing the truncated sorted p-values. It
#' is important that this vector: 1) contains only the truncated p-values (i.e,
#' those that fall below the truncation point) and 2) is sorted.
#' @param m_full The total (i.e., non-truncated) number of p-values.
#' @export
calc_truncatedTMTI_inf <- function(pvals, m_full) {
    .Call('_TMTI_calc_truncatedTMTI_inf', PACKAGE = 'TMTI', pvals, m_full)
}

